project_id = "kxjbankkuapchkezjjeq"

[functions.admin-reset-password]
verify_jwt = true

[functions.send-password-reset-confirmation]
verify_jwt = false

[functions.verify-blockchain-transaction]
verify_jwt = true

[functions.verify-confirmation-fee]
verify_jwt = true

[functions.send-blockchain-fee-notification]
verify_jwt = true

[functions.verify-withdrawal-confirmation-fee]
verify_jwt = true

[functions.send-fee-submission-notification]
verify_jwt = true
 
 [functions.send-withdrawal-notification]
 verify_jwt = true
 
 [functions.send-universal-notification]
 verify_jwt = true
