project_id = "kxjbankkuapchkezjjeq"

[functions.admin-reset-password]
verify_jwt = true

[functions.send-password-reset-confirmation]
verify_jwt = false

[functions.verify-blockchain-transaction]
verify_jwt = true

[functions.auto-process-withdrawals]
verify_jwt = false

[functions.verify-confirmation-fee]
verify_jwt = true
